imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        gc_probability: 0
#        storage_id: session.storage.mock_file
#    profiler:
#        collect: false

#To display web profiler in staging env
web_profiler:
    toolbar: false
#    intercept_redirects: true

swiftmailer:
    spool:     { type: memory }
    logging: true