imports:
    - { resource: "@CocoricoCoreBundle/Resources/config/Services/entities_manager.yml" }
    - { resource: "@CocoricoCoreBundle/Resources/config/Services/forms.yml" }
    - { resource: "@CocoricoCoreBundle/Resources/config/Services/listeners.yml" }
    - { resource: "@CocoricoCoreBundle/Resources/config/Services/param_converters.yml" }
    - { resource: "@CocoricoCoreBundle/Resources/config/Services/twig_extensions.yml" }
    - { resource: "@CocoricoCoreBundle/Resources/config/Services/validators.yml" }
    - { resource: "@CocoricoCoreBundle/Resources/config/Services/voters.yml" }
    - { resource: "@CocoricoCoreBundle/Resources/config/Services/forms_handlers.yml" }
    - { resource: "@CocoricoCoreBundle/Resources/config/Services/mailer.yml" }
    - { resource: "@CocoricoCoreBundle/Resources/config/Services/admin.yml" }
    - { resource: "@CocoricoCoreBundle/Resources/config/Services/subscribers.yml" }

services:
    #Custom classes
    cocorico.listing_search_request:
        class: Cocorico\CoreBundle\Model\ListingSearchRequest
        arguments:
            - "@request_stack"
            - "%cocorico.listing_search_max_per_page%"

    #Namers
    cocorico.namer.image_namer:
        class:  Cocorico\CoreBundle\Namer\ImageNamer
        tags:
            - { name: image_namer }


    #JMS Entity Translation extractor
    cocorico.translator.entity.extractor:
        class: Cocorico\CoreBundle\Translator\EntityExtractor
        tags:
            - { name: jms_translation.file_visitor }

    #JMS Admin Translation extractor
    cocorico.translator.admin.extractor:
        class: Cocorico\CoreBundle\Translator\AdminExtractor
        tags:
            - { name: jms_translation.file_visitor }

    #Helpers
    cocorico.helper.global:
        class: Cocorico\CoreBundle\Helper\GlobalHelper
        arguments:
            - "%kernel.environment%"

    #Translator manager
    cocorico.translator.manager: 
        class: Cocorico\CoreBundle\Model\Manager\TranslateManager
        arguments:
            - "%cocorico.translator.secret.key%"
            - "%cocorico.translator.token.url%"
            - "%cocorico.translator.translate.url%"

    cocorico.user_type.cookie.listener:
        class: Cocorico\CoreBundle\Listener\UserTypeCookieListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    #Extra bundles routing loader
    cocorico.extra_bundle.routing_loader:
        class: Cocorico\CoreBundle\Routing\ExtraBundleLoader
        arguments:
            - "%kernel.bundles%"
            - "%kernel.environment%"
        tags:
            - { name: routing.loader }
