imports:
    - { resource: subscribers.yml }
    - { resource: mailer.yml }
    - { resource: admin.yml }

#FOS Message services overriden
services:
    cocorico_message.new_thread.form.type:
        class: Cocorico\MessageBundle\Form\Type\Frontend\NewThreadMessageFormType
        arguments: ["%fos_message.thread_class%"]
        tags:
            - { name: form.type }
        public: true


    cocorico_message.new_thread.form.handler:
        class: Cocorico\MessageBundle\FormHandler\NewThreadMessageFormHandler
        arguments:
            - "@request_stack"
            - "@fos_message.composer"
            - "@fos_message.sender"
            - "@fos_message.participant_provider"
        public: false


    cocorico_message.reply.form.type:
        class: Cocorico\MessageBundle\Form\Type\Frontend\ReplyMessageFormType
        arguments: ["%fos_message.thread_class%"]
        tags:
            - { name: form.type }
        public: true


    cocorico_message.reply.form.handler:
        class: Cocorico\MessageBundle\FormHandler\ReplyMessageFormHandler
        arguments:
            - "@request_stack"
            - "@fos_message.composer"
            - "@fos_message.sender"
            - "@fos_message.participant_provider"
        public: false


    cocorico_message.composer:
        class: Cocorico\MessageBundle\Composer\Composer
        arguments:
            - "@fos_message.message_manager"
            - "@fos_message.thread_manager"
        public: false

    cocorico_message.thread_manager:
        class: Cocorico\MessageBundle\Model\ThreadManager
        arguments:
            - "@fos_message.thread_manager"
            - "@fos_message.message_manager"
            - "@cocorico_user.mailer.twig_swift"
            - "%cocorico.message_max_per_page%"
