services:
    #Listing
    cocorico.form.handler.listing:
        class: Cocorico\CoreBundle\Form\Handler\Frontend\ListingFormHandler
        arguments:
            - "@request_stack"
            - "@cocorico.listing.manager"
            - "@cocorico_user.form.handler.registration"
#        scope: request

    #Booking
    cocorico.form.handler.booking:
        class: Cocorico\CoreBundle\Form\Handler\Frontend\BookingFormHandler
        arguments:
            - "@request_stack"
            - "@cocorico.booking.manager"
            - "@cocorico_user.form.handler.registration"
#        scope: request

    cocorico.form.handler.booking.dashboard:
        abstract:  true
        calls:
            - [setRequest, ["@request_stack"]]
            - [setBookingManager, ["@cocorico.booking.manager"]]
            - [setThreadManager, ["@cocorico_message.thread_manager"]]
            - [setMinStartDelay, ["%cocorico.booking.min_start_delay%"]]
            - [setMinStartTimeDelay, ["%cocorico.booking.min_start_time_delay%"]]

    cocorico.form.handler.booking.offerer.dashboard:
        class: Cocorico\CoreBundle\Form\Handler\Dashboard\BookingOffererFormHandler
        parent: cocorico.form.handler.booking.dashboard
#        scope: request

    cocorico.form.handler.booking.asker.dashboard:
        class: Cocorico\CoreBundle\Form\Handler\Dashboard\BookingAskerFormHandler
        parent: cocorico.form.handler.booking.dashboard
#        scope: request

    cocorico.form.handler.booking_price:
        class: Cocorico\CoreBundle\Form\Handler\Frontend\BookingPriceFormHandler
        arguments:
            - "@session"
            - "@cocorico.form.type.booking_price"
            - "@request_stack"
            - "@cocorico.listing_search_request"
            - "@cocorico.booking.manager"

    #Listing Availability
    cocorico.form.handler.listing_availability.dashboard:
        abstract:  true
        calls:
            - [setRequest, ["@request_stack"]]
            - [setListingAvailabilityManager, ["@cocorico.listing_availability.manager"]]
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]

    cocorico.form.handler.listing_availability.price.dashboard:
        class: Cocorico\CoreBundle\Form\Handler\Dashboard\ListingAvailabilityPriceFormHandler
        parent: cocorico.form.handler.listing_availability.dashboard
#        scope: request

    cocorico.form.handler.listing_availability.status.dashboard:
        class: Cocorico\CoreBundle\Form\Handler\Dashboard\ListingAvailabilityStatusFormHandler
        parent: cocorico.form.handler.listing_availability.dashboard
#        scope: request

