parameters:
    cocorico.booking_request_offerer.sms.template: "CocoricoCoreBundle:SMS/Offerer:booking_request_offerer.txt.twig"
    cocorico.booking_request_asker.sms.template: "CocoricoCoreBundle:SMS/Asker:booking_request_asker.txt.twig"
    cocorico.booking_accepted_offerer.sms.template: "CocoricoCoreBundle:SMS/Offerer:booking_accepted_offerer.txt.twig"
    cocorico.booking_accepted_asker.sms.template: "CocoricoCoreBundle:SMS/Asker:booking_accepted_asker.txt.twig"
    cocorico.booking_refused_offerer.sms.template: "CocoricoCoreBundle:SMS/Offerer:booking_refused_offerer.txt.twig"
    cocorico.booking_refused_asker.sms.template: "CocoricoCoreBundle:SMS/Asker:booking_refused_asker.txt.twig"
    cocorico.booking_request_expired_asker.sms.template: "CocoricoCoreBundle:SMS/Asker:booking_request_expired_asker.txt.twig"
    cocorico.booking_request_expired_offerer.sms.template: "CocoricoCoreBundle:SMS/Offerer:booking_request_expired_offerer.txt.twig"
    cocorico.booking_canceled_by_asker_offerer.sms.template: "CocoricoCoreBundle:SMS/Offerer:booking_canceled_by_asker_offerer.txt.twig"
    cocorico.booking_canceled_by_asker_asker.sms.template: "CocoricoCoreBundle:SMS/Asker:booking_canceled_by_asker_asker.txt.twig"
    cocorico.booking_imminent_offerer.sms.template: "CocoricoCoreBundle:SMS/Offerer:booking_imminent_offerer.txt.twig"
    cocorico.booking_imminent_asker.sms.template: "CocoricoCoreBundle:SMS/Asker:booking_imminent_asker.txt.twig"
    cocorico.booking_request_expiration_alert_offerer.sms.template: "CocoricoCoreBundle:SMS/Offerer:booking_request_expiration_alert_offerer.txt.twig"
    cocorico.admin_message.sms.template: "CocoricoCoreBundle:SMS:admin_message.txt.twig"

services:
    cocorico.smser.twig:
        class: Cocorico\CoreBundle\Smser\TwigSmser
        arguments:
            - "@router"
            - "@twig"
            - "@request_stack"
            - parameters:
                cocorico_locales: %cocorico.locales%
                cocorico_locale: %cocorico.locale%
                cocorico_contact_mail: "%cocorico.contact_mail%"
            - templates:
                booking_request_offerer: %cocorico.booking_request_offerer.sms.template%
                booking_accepted_offerer: %cocorico.booking_accepted_offerer.sms.template%
                booking_canceled_by_asker_offerer: %cocorico.booking_canceled_by_asker_offerer.sms.template%
                booking_canceled_by_asker_asker: %cocorico.booking_canceled_by_asker_asker.sms.template%
                booking_request_expired_offerer: %cocorico.booking_request_expired_offerer.sms.template%
                booking_request_expired_asker: %cocorico.booking_request_expired_asker.sms.template%
                booking_request_asker: %cocorico.booking_request_asker.sms.template%
                booking_accepted_asker: %cocorico.booking_accepted_asker.sms.template%
                booking_refused_asker: %cocorico.booking_refused_asker.sms.template%
                booking_refused_offerer: %cocorico.booking_refused_offerer.sms.template%
                booking_imminent_offerer: %cocorico.booking_imminent_offerer.sms.template%
                booking_imminent_asker: %cocorico.booking_imminent_asker.sms.template%
                booking_request_expiration_alert_offerer: %cocorico.booking_request_expiration_alert_offerer.sms.template%
                admin_message: %cocorico.admin_message.sms.template%
            - "@?cocorico_sms.sender"