services:
    #Twig
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    #Global twig variables
    cocorico.twig.core_extension:
        class: Cocorico\CoreBundle\Twig\CoreExtension
        arguments:
            - "@lexik_currency.currency_extension"
            - "@translator.default"
            - "@session"
            - parameters:
                cocorico_locales: "%cocorico.locales%"
                cocorico_time_unit: "%cocorico.time_unit%"
                cocorico_time_zone: "%cocorico.time_zone%"
                cocorico_time_unit_allday: "%cocorico.time_unit_allday%"
                cocorico_time_unit_flexibility: "%cocorico.time_unit_flexibility%"
                cocorico_time_hours_available: "%cocorico.time_hours_available%"
                cocorico_days_display_mode: "%cocorico.days_display_mode%"
                cocorico_times_display_mode: "%cocorico.times_display_mode%"
                cocorico_currencies: "%cocorico.currencies%"
                cocorico_currency: "%cocorico.currency%"
                cocorico_fee_as_offerer: "%cocorico.fee_as_offerer%"
                cocorico_fee_as_asker: "%cocorico.fee_as_asker%"
                cocorico_listing_availability_status: "%cocorico.listing_availability_status%"
                cocorico_listing_price_precision: "%cocorico.listing_price_precision%"
                cocorico_listing_price_min: "%cocorico.listing_price_min%"
                cocorico_listing_price_max: "%cocorico.listing_price_max%"
                cocorico_listing_map_display_marker: "%cocorico.listing_map_display_marker%"
                cocorico_listing_search_min_result: "%cocorico.listing_search_min_result%"
                cocorico_listing_duplication: "%cocorico.listing.duplication%"
                cocorico_booking_allow_single_day: "%cocorico.booking.allow_single_day%"
                cocorico_booking_end_day_included: "%cocorico.booking.end_day_included%"
                cocorico_booking_expiration_delay: "%cocorico.booking.expiration_delay%"
                cocorico_booking_acceptation_delay: "%cocorico.booking.acceptation_delay%"
                cocorico_booking_validated_moment: "%cocorico.booking.validated_moment%"
                cocorico_booking_validated_delay: "%cocorico.booking.validated_delay%"
                cocorico_booking_price_min: "%cocorico.booking_price_min%"
                cocorico_booking_min_start_time_delay: "%cocorico.booking.min_start_time_delay%"
                cocorico_vat: "%cocorico.vat%"
                cocorico_include_vat: "%cocorico.include_vat%"
                cocorico_display_vat: "%cocorico.display_vat%"
                cocorico_user_address_delivery: "%cocorico.user_address_delivery%"
        tags:
            - { name: twig.extension }

    lexik_currency.currency_extension:
        class: "%lexik_currency.currency_extension.class%"
        arguments:
            - "@service_container"
        tags:
            - { name: twig.extension }

    cocorico.twig.language_extension:
        class: Cocorico\CoreBundle\Twig\LanguageExtension
        tags:
            - { name: twig.extension }

    cocorico.twig.country_extension:
        class: Cocorico\CoreBundle\Twig\CountryExtension
        tags:
            - { name: twig.extension }

    cocorico.twig.extra_bundle_extension:
        class: Cocorico\CoreBundle\Twig\ExtraBundleExtension
        arguments:
            - "%kernel.bundles%"
        tags:
            - { name: twig.extension }