services:
    #Voters
    security.access.listing_voter:
        class:      Cocorico\CoreBundle\Security\Voter\ListingVoter
        public:     false
        tags:
           - { name: security.voter }

    security.access.listing_image_voter:
        class:      Cocorico\CoreBundle\Security\Voter\ListingImageVoter
        public:     false
        tags:
           - { name: security.voter }

    security.access.booking_voter:
        class:      Cocorico\CoreBundle\Security\Voter\BookingVoter
        public:     false
        tags:
           - { name: security.voter }
