cocorico_user_frontend:
    resource: "@CocoricoUserBundle/Controller/"
    type:     annotation

cocorico_user_dashboard:
    resource: "@CocoricoUserBundle/Controller/Dashboard"
    type:     annotation
    prefix: /dashboard

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /%cocorico.admin%
    options: { i18n: false }

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /%cocorico.admin%/user
    options: { i18n: false }

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /login

hwi_facebook_login:
    pattern: /oauth/fb-login
